# Generated by Django 2.1 on 2018-08-23 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello.Stock')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hello.User')),
            ],
        ),
    ]
